### ISSUE TITLE
Set up lints, analysis presubmit, test presubmit

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/macros#2]

**Comment by davidmorgan** [comment]
@jakemac53 do you happen to know a monorepo that's a good example to follow, please? :)

Always happy to hack something random, but I guess following best practices would be better ;)

**Comment by jakemac53** [comment]
I would follow test or build, using mono_repo to generate the github configs

**Comment by jakemac53** [comment]
We should use the new pub workspace feature too (see the dart-lang/build)

**Comment by jakemac53** [comment]
@davidmorgan if you want I could set up mono_repo here pretty quickly, but don't want to step on your toes if you are already working towards getting CI set up

**Comment by davidmorgan** [comment]
@jakemac53 yes please :)
