### ISSUE TITLE
Macros for Freezed

### ISSUE THREAD

**Issue by amrgetment** [dart-lang/macros#56]
I wonder if you could support @rrousselGit so he could migrate his library to macros

https://pub.dev/packages/freezed/versions/3.0.0-0.0.dev

<img width="734" alt="image" src="https://github.com/user-attachments/assets/66b2619c-4126-4611-94dd-ada09c9784b7">

**Comment by davidmorgan** [comment]
Thanks! We are aware of freezed, of course :) and will do what we can to support it.

There's nothing specific we can do in that regard right now though, we are in the middle of a number of large breaking changes, we'll take another look afterwards. So I'll close this for now. I think we already have discussion / more specific issues for the technical pieces, if not feel free to open some. Thanks.

**Comment by amrgetment** [comment]
Thanks a lot, build_runner is slow, so macros will save developers a lot of wasted time

**Comment by davidmorgan** [comment]
That's the plan, yes :)

**Comment by amrgetment** [comment]
@davidmorgan I wonder what is the main ticket or feature that is missing to make Freezed library work with macros?

**Comment by davidmorgan** [comment]
The main thing that's missing is that macros aren't released yet :)

For individual features, the features table at the end o https://pub.dev/packages/freezed/versions/3.0.0-0.0.dev gives some idea.

**Comment by amrgetment** [comment]
yes it mentions 
>Requires macros to be more developed
so I wonder for these features, what kind of missing functionality in macros to support it?
```
default values
deep copy 
generic classes
```

**Comment by davidmorgan** [comment]
I believe the features corresponding to those three are: support for forwarding defaults, support for generating classes based on fields, and for generics :)

**Comment by amrgetment** [comment]
Thanks a lot for your efforts in developing macros and support
