### ISSUE TITLE
Push resolved model into macro scope?

### ISSUE THREAD

**Issue by simolus3** [dart-lang/macros#73]
A while back, we've briefly discussed the idea of putting resolved models into a `Zone` to make models globally accessible: https://github.com/dart-lang/macros/pull/37#issuecomment-2283794860.
Given that scopes have since been implemented, I wonder if resolved `Model`s in macros should be added to the respective macro scope, making the model globally accessible. With an accessible model (and derived structures like `StaticTypeSystem` that could then be cached alongside the model), some APIs would be easier to access (e.g. we could have a `isSubtypeOf` extension on type models instead of forcing users to explicitly construct a type system).

If this is still something that sounds worth exploring, I'm happy to make a contribution in this direction. A big question is how we'd deal with macros calling `query` multiple times, but IIRC we're supposed to be able to combine models eventually so we could still keep an internal model that we add information to on each query result?

**Comment by davidmorgan** [comment]
Hi Simon :)

Yes, definitely, that sounds like a good area to explore, I'll be happy to review PRs, whether work in progress experimentation or landable.

The [json_codable macro](https://github.com/dart-lang/macros/blob/main/pkgs/_test_macros/lib/json_codable.dart) has quite a few TODOs around doing checking of types, in case that's useful to refer to; it's based on the experimental release [here](https://github.com/dart-lang/sdk/blob/main/pkg/json/lib/json.dart) that does do the checks.

Yes, I think accumulating the information from multiple queries is the right way to go.

Thanks!
