### ISSUE TITLE
Is macros supports files or it watches classes only 

### ISSUE THREAD

**Issue by amrgetment** [dart-lang/macros#88]
I use this library that converts assets' files to dart strings
For example `assets/images/avatar.png` to `Assets.images.avatar`
https://pub.dev/packages/assets_scanner

So I wonder is macros can do that in the future or it can’t watch the assets changes?

**Comment by davidmorgan** [comment]
That seems a reasonable thing to support.

But we haven't done any concrete design or implementation related to file support, so "seems reasonable" is the most I can say for now :)

I guess any updates will go on https://github.com/dart-lang/language/issues/3952, so please watch that if you want to follow along. Closing this one as answered :)

**Comment by amrgetment** [comment]
Thanks a lot
